version: 2.1
orbs:
  cypress: cypress-io/cypress@1.22.0
  codecov: codecov/codecov@1.0.5

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Commands ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
commands:
  report-coverage:
    steps:
      - store_artifacts:
          path: coverage
      - run: npx nyc report --reporter=text || true
      - codecov/upload:
          file: coverage/coverage-final.json

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Workflows ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
workflows:
  build:
    jobs:
      # Setup
      #  1. Install Cypress
      #  2. Validate types
      #  3. Run server unit-tests
      - cypress/install:
          name: "Setup"
          yarn: true
          executor: cypress/browsers-chrome78-ff70
          post-steps:
            - run:
                name: Check Types
                command: yarn types
            - run:
                name: Run Unit Tests
                command: yarn test:unit:ci

      # Run API tests against backend server
      - cypress/run:
          name: "API Tests"
          browser: chrome
          spec: cypress/tests/api/*
          executor: cypress/browsers-chrome78-ff70
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start:ci
          record: true
          parallel: true
          parallelism: 5
          group: API
          requires:
            - Setup
          post-steps:
            - store-coverage-report

      # Run E2E tests in Chrome
      - cypress/run:
          name: "UI Tests - Chrome"
          browser: chrome
          spec: cypress/tests/ui/*
          executor: cypress/browsers-chrome78-ff70
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start:ci
          record: true
          parallel: true
          parallelism: 5
          group: "UI - Chrome"
          requires:
            - Setup
          post-steps:
            - store-coverage-report

      # Run E2E tests in Chrome with mobile device viewport
      - cypress/run:
          name: "UI Tests - Chrome - Mobile"
          browser: chrome
          spec: cypress/tests/ui/*
          config: "viewportWidth=375,viewportHeight=667"
          executor: cypress/browsers-chrome78-ff70
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start:ci
          record: true
          parallel: true
          parallelism: 5
          group: "UI - Chrome - Mobile"
          requires:
            - Setup
          post-steps:
            - store-coverage-report

      # Run E2E tests in Firefox
      - cypress/run:
          name: "UI Tests - Firefox"
          browser: firefox
          spec: cypress/tests/ui/*
          executor: cypress/browsers-chrome78-ff70
          wait-on: "http://localhost:3000"
          yarn: true
          start: yarn start:ci
          record: true
          parallel: true
          parallelism: 4
          group: "UI - Firefox"
          requires:
            - Setup
          post-steps:
            - store-coverage-report

      # Run E2E tests in Firefox with mobile device viewport
      - cypress/run:
          name: "UI Tests - Firefox - Mobile"
          browser: firefox
          spec: cypress/tests/ui/*
          config: "viewportWidth=375,viewportHeight=667"
          wait-on: "http://localhost:3000"
          executor: cypress/browsers-chrome78-ff70
          yarn: true
          start: yarn start:ci
          record: true
          parallel: true
          parallelism: 4
          group: "UI - Firefox - Mobile"
          requires:
            - Setup
          post-steps:
            - store-coverage-report
