version: 2.1
orbs:
  cypress: cypress-io/cypress@1.21.0
executors:
  mobile:
    docker:
      - image: cypress/browsers-chrome78-ff70
    environment:
      # iPhone 6 viewport dimensions
      CYPRESS_VIEWPORT_WIDTH: 375
      CYPRESS_VIEWPORT_HEIGHT: 667
workflows:
  build:
    jobs:
      # Setup
      #  1. Install Cypress
      #  2. Build application
      #  3. Validate types
      #  4. Run server unit-tests
      - cypress/install:
          name: "Setup"
          yarn: true
          executor: cypress/browsers-chrome78-ff70
          build: "npm run build"
          post-steps:
            - run:
                name: Check Types
                command: yarn types
            - run:
                name: Unit Tests
                command: yarn test:unit

      # Run API tests against backend server
      - cypress/run:
          name: "API Tests"
          requires:
            - Setup
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          yarn: true
          start: yarn test:ci
          wait-on: "http://localhost:3000"
          record: true
          spec: cypress/tests/api/*
          parallel: true
          parallelism: 4
          group: API

      # Run E2E tests in Chrome
      - cypress/run:
          name: "UI Tests - Chrome"
          requires:
            - Setup
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          yarn: true
          start: yarn test:ci
          wait-on: "http://localhost:3000"
          record: true
          parallel: true
          parallelism: 4
          spec: cypress/tests/ui/*
          group: "UI - Chrome"

      # Run E2E tests in Chrome with mobile device viewport
      - cypress/run:
          name: "UI Tests - Chrome - Mobile"
          requires:
            - Setup
          executor: mobile
          browser: chrome
          yarn: true
          start: yarn test:ci
          wait-on: "http://localhost:3000"
          record: true
          parallel: true
          parallelism: 4
          spec: cypress/tests/ui/*
          group: "UI - Chrome - Mobile"

      # Run E2E tests in Firefox
      - cypress/run:
          name: "UI Tests - Firefox"
          requires:
            - Setup
          executor: cypress/browsers-chrome78-ff70
          browser: firefox
          yarn: true
          start: yarn test:ci
          wait-on: "http://localhost:3000"
          record: true
          parallel: true
          parallelism: 4
          spec: cypress/tests/ui/*
          group: "UI - Firefox"

      # Run E2E tests in Firefox with mobile device viewport
      - cypress/run:
          name: "UI Tests - Firefox - Mobile"
          requires:
            - Setup
          executor: mobile
          browser: firefox
          yarn: true
          start: yarn test:ci
          wait-on: "http://localhost:3000"
          record: true
          parallel: true
          parallelism: 4
          spec: cypress/tests/ui/*
          group: "UI - Firefox - Mobile"
