name: Cypress Tests
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.14.1-chrome85-ff81
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - run: yarn types
      - run: yarn test:unit:ci
  tests:
    runs-on: ubuntu-latest
    needs: install
    # strategy:
    #   # when one test fails, DO NOT cancel the other
    #   # containers, because this will kill Cypress processes
    #   # leaving the Dashboard hanging ...
    #   # https://github.com/cypress-io/github-action/issues/48
    #   fail-fast: false
    #   matrix:
    #     # run copies of the current job in parallel
    #     containers: [1, 2]
    steps:
      - run: yarn test:unit:ci
      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v2
        with:
          install: false
          browser: chrome
          record: true
          parallel: true
          group: "UI - Chrome" 
          spec: cypress/tests/ui/*
          start: yarn start:ci
          wait-on: "http://localhost:3000"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}