name: Run E2E Tests

on: [push]

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
   # container:
      #image: cypress/browsers:node18.12.0-chrome106-ff106
     # options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      - run: yarn cypress info
      - run: node --version
      - run: node -p 'os.cpus()'
      - run: yarn types
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.16.1'
      - name: Install dependencies
        run: yarn install
        
      #- name: Set up Python
        #uses: actions/setup-python@v2
        #with:
         # python-version: 3.11

      - name: Integrate Shipyard
        uses: shipyard/github-action/fetch-shipyard-env@1.0.1
        with:
          api-token: ${{ secrets.SHIPYARD_API_TOKEN }}
          timeout-minutes: "10"
      - name: Print Env Data
        run: |
          export CYPRESS_BASE_URL=${SHIPYARD_ENVIRONMENT_URL}
          export CYPRESS_BYPASS_TOKEN=${SHIPYARD_BYPASS_TOKEN}
          env | grep -e SHIPYARD -e CYPRESS
        shell: bash
        
      - name: Run E2E tests against the ephemeral environment
        run: yarn cypress:run --spec "cypress/tests/shipyard/manage-user.tsx"
        shell: bash
        env:
            CYPRESS_BASE_URL: ${SHIPYARD_ENVIRONMENT_URL}
            CYPRESS_BYPASS_TOKEN: ${SHIPYARD_BYPASS_TOKEN}
